"""added new interpolated points db

Revision ID: 017aa869b17f
Revises: 6a75c07f2def
Create Date: 2026-06-30 11:15:55.393478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017aa869b17f'
down_revision: Union[str, Sequence[str], None] = '6a75c07f2def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpolated_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.Column('heat_risk', sa.Float(), nullable=True),
    sa.Column('crowd_density', sa.Float(), nullable=True),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('cooling_centers', sa.Float(), nullable=True),
    sa.Column('infrastructure_strain', sa.Float(), nullable=True),
    sa.Column('interpolation_method', sa.Text(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cell_geometry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interpolated_points_grid_cell_id'), 'interpolated_points', ['grid_cell_id'], unique=False)
    op.create_index(op.f('ix_interpolated_points_timestamp'), 'interpolated_points', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interpolated_points_timestamp'), table_name='interpolated_points')
    op.drop_index(op.f('ix_interpolated_points_grid_cell_id'), table_name='interpolated_points')
    op.drop_table('interpolated_points')
    # ### end Alembic commands ###
