"""new tables

Revision ID: 4328ba02df79
Revises: 50276214e922
Create Date: 2026-07-21 17:10:31.796492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4328ba02df79'
down_revision: Union[str, Sequence[str], None] = '50276214e922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heat_data_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('avg_temp_c', sa.Float(), nullable=False),
    sa.Column('relative_humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed_knots', sa.Float(), nullable=False),
    sa.Column('urban_heat_idx', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), server_default='interpolated', nullable=False),
    sa.Column('distance_nearest_station_km', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('passed_threshold', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_meteo_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('timezone_abbreviation', sa.Text(), nullable=True),
    sa.Column('utc_offset_seconds', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Float(), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_current', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_hourly', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_daily', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forecast_days', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'open_meteo'"), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_meteo_forecasts_fetched_at'), 'open_meteo_forecasts', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_open_meteo_forecasts_latitude'), 'open_meteo_forecasts', ['latitude'], unique=False)
    op.create_index(op.f('ix_open_meteo_forecasts_longitude'), 'open_meteo_forecasts', ['longitude'], unique=False)
    op.create_table('polygon_geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city_name', sa.Text(), nullable=True),
    sa.Column('state_name', sa.Text(), nullable=True),
    sa.Column('color', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polygon_geometry_city_name'), 'polygon_geometry', ['city_name'], unique=False)
    op.create_index(op.f('ix_polygon_geometry_state_name'), 'polygon_geometry', ['state_name'], unique=False)
    op.create_table('prediction_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pred_longitude', sa.Float(), nullable=False),
    sa.Column('pred_latitude', sa.Float(), nullable=False),
    sa.Column('pred_model_name', sa.Text(), nullable=False),
    sa.Column('pred_metrics', sa.JSON(), nullable=False),
    sa.Column('pred_color', sa.Text(), nullable=False),
    sa.Column('pred_polygon_grid', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_table_pred_latitude'), 'prediction_table', ['pred_latitude'], unique=False)
    op.create_index(op.f('ix_prediction_table_pred_longitude'), 'prediction_table', ['pred_longitude'], unique=False)
    op.create_index(op.f('ix_prediction_table_pred_model_name'), 'prediction_table', ['pred_model_name'], unique=False)
    op.create_table('visitor_data_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('source_market', sa.Text(), nullable=True),
    sa.Column('fsq_place_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('visitor_count', sa.Integer(), nullable=True),
    sa.Column('visitor_count_source', sa.Text(), nullable=True),
    sa.Column('market_brand_visitor_count_total', sa.Integer(), nullable=True),
    sa.Column('candidate_foursquare_poi_count', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.Text(), nullable=True),
    sa.Column('visitor_categories', sa.Text(), nullable=True),
    sa.Column('nearest_heat_distance_km', sa.Float(), nullable=True),
    sa.Column('query_center_distance_m', sa.Float(), nullable=True),
    sa.Column('google_maps_congestion', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_spend_brand_state_rice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('spend_amount', sa.Float(), nullable=False),
    sa.Column('state_abbr', sa.Text(), nullable=False),
    sa.Column('trans_count', sa.Float(), nullable=False),
    sa.Column('trans_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_spend_brand_state_rice_brand_id'), 'daily_spend_brand_state_rice', ['brand_id'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_brand_name'), 'daily_spend_brand_state_rice', ['brand_name'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_market'), 'daily_spend_brand_state_rice', ['market'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_state_abbr'), 'daily_spend_brand_state_rice', ['state_abbr'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_trans_date'), 'daily_spend_brand_state_rice', ['trans_date'], unique=False)
    op.create_table('daily_weather_rice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_dew_point_f', sa.Float(), nullable=False),
    sa.Column('average_relative_humidity', sa.Float(), nullable=False),
    sa.Column('average_sea_level_pressure_millibars', sa.Float(), nullable=False),
    sa.Column('average_temperature_c', sa.Float(), nullable=False),
    sa.Column('average_visibility_km', sa.Float(), nullable=False),
    sa.Column('average_wind_speed_knots', sa.Float(), nullable=False),
    sa.Column('city_location_identifier', sa.Text(), nullable=False),
    sa.Column('cooling_degree_days_c', sa.Float(), nullable=False),
    sa.Column('heating_degree_days_c', sa.Float(), nullable=False),
    sa.Column('max_temperature_c', sa.Float(), nullable=False),
    sa.Column('min_temperature_c', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Integer(), nullable=False),
    sa.Column('valid_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_weather_rice_city_location_identifier'), 'daily_weather_rice', ['city_location_identifier'], unique=False)
    op.create_index(op.f('ix_daily_weather_rice_valid_date'), 'daily_weather_rice', ['valid_date'], unique=False)
    op.create_table('interpolated_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.Column('heat_risk', sa.Float(), nullable=True),
    sa.Column('crowd_density', sa.Float(), nullable=True),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('cooling_centers', sa.Float(), nullable=True),
    sa.Column('infrastructure_strain', sa.Float(), nullable=True),
    sa.Column('predicted_heat_index', sa.Float(), nullable=True),
    sa.Column('predicted_heat_risk', sa.Float(), nullable=True),
    sa.Column('predicted_crowd_density', sa.Float(), nullable=True),
    sa.Column('predicted_population', sa.Float(), nullable=True),
    sa.Column('predicted_visitor_count', sa.Float(), nullable=True),
    sa.Column('interpolation_method', sa.Text(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cell_geometry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interpolated_points_grid_cell_id'), 'interpolated_points', ['grid_cell_id'], unique=False)
    op.create_index(op.f('ix_interpolated_points_timestamp'), 'interpolated_points', ['timestamp'], unique=False)
    op.create_table('polygon_impact_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polygon_geometry_id', sa.Integer(), nullable=False),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cell_geometry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['polygon_geometry_id'], ['polygon_geometry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polygon_geometry_id', 'grid_cell_id', name='uq_polygon_impact_grid')
    )
    op.create_index(op.f('ix_polygon_impact_grids_grid_cell_id'), 'polygon_impact_grids', ['grid_cell_id'], unique=False)
    op.create_index(op.f('ix_polygon_impact_grids_polygon_geometry_id'), 'polygon_impact_grids', ['polygon_geometry_id'], unique=False)
    op.create_table('spend_patterns_rice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brands', sa.Text(), nullable=True),
    sa.Column('bucketed_customer_frequency', sa.JSON(), nullable=False),
    sa.Column('bucketed_customer_incomes', sa.JSON(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('customer_home_city', sa.JSON(), nullable=False),
    sa.Column('day_counts', sa.JSON(), nullable=False),
    sa.Column('iso_country_code', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('mean_spend_per_customer_by_frequency', sa.JSON(), nullable=False),
    sa.Column('mean_spend_per_customer_by_income', sa.JSON(), nullable=False),
    sa.Column('median_spend_per_customer', sa.Float(), nullable=False),
    sa.Column('median_spend_per_transaction', sa.Float(), nullable=False),
    sa.Column('naics_code', sa.Integer(), nullable=False),
    sa.Column('online_spend', sa.Float(), nullable=False),
    sa.Column('online_transactions', sa.Float(), nullable=False),
    sa.Column('parent_placekey', sa.Text(), nullable=True),
    sa.Column('placekey', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.Text(), nullable=False),
    sa.Column('raw_num_customers', sa.Float(), nullable=False),
    sa.Column('raw_num_transactions', sa.Float(), nullable=False),
    sa.Column('raw_total_spend', sa.Float(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('related_buynowpaylater_service_pct', sa.JSON(), nullable=True),
    sa.Column('related_cross_shopping_local_brands_pct', sa.JSON(), nullable=True),
    sa.Column('related_cross_shopping_online_merchants_pct', sa.JSON(), nullable=True),
    sa.Column('related_cross_shopping_physical_brands_pct', sa.JSON(), nullable=True),
    sa.Column('related_cross_shopping_same_category_brands_pct', sa.JSON(), nullable=True),
    sa.Column('related_delivery_service_pct', sa.JSON(), nullable=True),
    sa.Column('related_payment_platform_pct', sa.JSON(), nullable=True),
    sa.Column('related_rideshare_service_pct', sa.JSON(), nullable=True),
    sa.Column('related_streaming_cable_pct', sa.JSON(), nullable=True),
    sa.Column('related_wireless_carrier_pct', sa.JSON(), nullable=True),
    sa.Column('spend_by_day', sa.JSON(), nullable=False),
    sa.Column('spend_by_day_of_week', sa.JSON(), nullable=False),
    sa.Column('spend_by_transaction_intermediary', sa.JSON(), nullable=True),
    sa.Column('spend_date_range_start', sa.Date(), nullable=False),
    sa.Column('spend_date_range_end', sa.Date(), nullable=False),
    sa.Column('spend_pct_change_vs_prev_month', sa.Float(), nullable=True),
    sa.Column('spend_pct_change_vs_prev_year', sa.Float(), nullable=True),
    sa.Column('spend_per_transaction_by_day', sa.JSON(), nullable=False),
    sa.Column('spend_per_transaction_percentiles', sa.JSON(), nullable=False),
    sa.Column('street_address', sa.Text(), nullable=False),
    sa.Column('sub_category', sa.Text(), nullable=False),
    sa.Column('top_category', sa.Text(), nullable=False),
    sa.Column('transaction_intermediary', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spend_patterns_rice_brands'), 'spend_patterns_rice', ['brands'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_city'), 'spend_patterns_rice', ['city'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_latitude'), 'spend_patterns_rice', ['latitude'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_longitude'), 'spend_patterns_rice', ['longitude'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_market'), 'spend_patterns_rice', ['market'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_placekey'), 'spend_patterns_rice', ['placekey'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_region'), 'spend_patterns_rice', ['region'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_spend_date_range_end'), 'spend_patterns_rice', ['spend_date_range_end'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_spend_date_range_start'), 'spend_patterns_rice', ['spend_date_range_start'], unique=False)
    op.create_table('store_visits_rice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('daily_visits', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('naics_code', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('stock_exchange', sa.Text(), nullable=True),
    sa.Column('stock_symbol', sa.Text(), nullable=True),
    sa.Column('store_id', sa.Text(), nullable=False),
    sa.Column('sub_category', sa.Text(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_visits_rice_brand'), 'store_visits_rice', ['brand'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_business_name'), 'store_visits_rice', ['business_name'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_local_date'), 'store_visits_rice', ['local_date'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_market'), 'store_visits_rice', ['market'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_state'), 'store_visits_rice', ['state'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_store_id'), 'store_visits_rice', ['store_id'], unique=False)
    op.create_table('urban_heat_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('point_geometry', sa.Text(), nullable=False),
    sa.Column('uhi', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urban_heat_index_latitude'), 'urban_heat_index', ['latitude'], unique=False)
    op.create_index(op.f('ix_urban_heat_index_longitude'), 'urban_heat_index', ['longitude'], unique=False)
    op.create_index(op.f('ix_urban_heat_index_market'), 'urban_heat_index', ['market'], unique=False)
    op.create_table('weather_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('dewpoint', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Text(), nullable=True),
    sa.Column('precipitation_prob', sa.Float(), nullable=True),
    sa.Column('detailed_forecast', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cell_geometry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grid_cell_id', 'timestamp', 'source', name='uq_weather_observation_cell_timestamp_source')
    )
    op.create_index(op.f('ix_weather_observation_grid_cell_id'), 'weather_observation', ['grid_cell_id'], unique=False)
    op.create_index(op.f('ix_weather_observation_timestamp'), 'weather_observation', ['timestamp'], unique=False)
    op.alter_column('core_poi_geometry', 'brands',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('core_poi_geometry', 'category_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('core_poi_geometry', 'city',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'domains',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('core_poi_geometry', 'enclosed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'geometry_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'includes_parking_lot',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'iso_country_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'is_synthetic',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('core_poi_geometry', 'location_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('core_poi_geometry', 'market',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'open_hours',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('core_poi_geometry', 'placekey',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'polygon_class',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'polygon_wkt',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'postal_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'region',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'safegraph_place_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'street_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'sub_category',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'sub_category_2022',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'top_category',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'top_category_2022',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_poi_geometry', 'wkt_area_sq_meters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('core_poi_geometry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_core_poi_geometry_latitude'), 'core_poi_geometry', ['latitude'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_longitude'), 'core_poi_geometry', ['longitude'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_market'), 'core_poi_geometry', ['market'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_region'), 'core_poi_geometry', ['region'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_safegraph_place_id'), 'core_poi_geometry', ['safegraph_place_id'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_store_id'), 'core_poi_geometry', ['store_id'], unique=False)
    op.create_foreign_key(None, 'core_poi_geometry', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('grid_cell_geometry', 'state',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('grid_cell_geometry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('grid_cell_geometry_cell_id_key'), 'grid_cell_geometry', type_='unique')
    op.create_index(op.f('ix_grid_cell_geometry_cell_id'), 'grid_cell_geometry', ['cell_id'], unique=False)
    op.create_index(op.f('ix_grid_cell_geometry_col'), 'grid_cell_geometry', ['col'], unique=False)
    op.create_index(op.f('ix_grid_cell_geometry_row'), 'grid_cell_geometry', ['row'], unique=False)
    op.create_unique_constraint('uq_grid_cell_geometry_cell_id', 'grid_cell_geometry', ['cell_id'])
    op.create_unique_constraint('uq_grid_cell_geometry_row_col_state', 'grid_cell_geometry', ['row', 'col', 'state'])
    op.add_column('grid_cell_metrics', sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('grid_cell_metrics', sa.Column('heat_index', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('heat_risk', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('crowd_density', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('population', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('cooling_centers', sa.Integer(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('cooling_centers_impact_radius', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('infrastructure_strain', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('predicted_heat_index', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('predicted_heat_risk', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('predicted_crowd_density', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('predicted_population', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('predicted_visitor_count', sa.Float(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('visitor_metric_source', sa.Text(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('visitor_metric_is_placeholder', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('grid_cell_metrics', sa.Column('population_metric_source', sa.Text(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('population_metric_is_placeholder', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('grid_cell_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_grid_cell_metrics_grid_date'), table_name='grid_cell_metrics')
    op.drop_index(op.f('ix_grid_cell_metrics_source_kind'), table_name='grid_cell_metrics')
    op.create_index(op.f('ix_grid_cell_metrics_grid_cell_id'), 'grid_cell_metrics', ['grid_cell_id'], unique=False)
    op.create_index(op.f('ix_grid_cell_metrics_timestamp'), 'grid_cell_metrics', ['timestamp'], unique=False)
    op.drop_column('grid_cell_metrics', 'metric_source_kind')
    op.drop_column('grid_cell_metrics', 'relative_humidity')
    op.drop_column('grid_cell_metrics', 'wind_speed_knots')
    op.drop_column('grid_cell_metrics', 'placekey')
    op.drop_column('grid_cell_metrics', 'name')
    op.drop_column('grid_cell_metrics', 'category')
    op.drop_column('grid_cell_metrics', 'passed_threshold')
    op.drop_column('grid_cell_metrics', 'latitude')
    op.drop_column('grid_cell_metrics', 'source_market')
    op.drop_column('grid_cell_metrics', 'date')
    op.drop_column('grid_cell_metrics', 'uhi')
    op.drop_column('grid_cell_metrics', 'visitor_count_source')
    op.drop_column('grid_cell_metrics', 'fsq_place_id')
    op.drop_column('grid_cell_metrics', 'visitor_count')
    op.drop_column('grid_cell_metrics', 'distance_to_nearest_station_km')
    op.drop_column('grid_cell_metrics', 'market')
    op.drop_column('grid_cell_metrics', 'source_period_end')
    op.drop_column('grid_cell_metrics', 'source')
    op.drop_column('grid_cell_metrics', 'avg_temperature_c')
    op.drop_column('grid_cell_metrics', 'source_period_start')
    op.drop_column('grid_cell_metrics', 'longitude')
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('grid_cell_metrics', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('grid_cell_metrics', sa.Column('source_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('avg_temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('source_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('market', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('distance_to_nearest_station_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('visitor_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('fsq_place_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('visitor_count_source', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('uhi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('grid_cell_metrics', sa.Column('source_market', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('grid_cell_metrics', sa.Column('passed_threshold', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('placekey', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('wind_speed_knots', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('relative_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('metric_source_kind', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_grid_cell_metrics_timestamp'), table_name='grid_cell_metrics')
    op.drop_index(op.f('ix_grid_cell_metrics_grid_cell_id'), table_name='grid_cell_metrics')
    op.create_index(op.f('ix_grid_cell_metrics_source_kind'), 'grid_cell_metrics', ['metric_source_kind'], unique=False)
    op.create_index(op.f('ix_grid_cell_metrics_grid_date'), 'grid_cell_metrics', ['grid_cell_id', 'date'], unique=False)
    op.alter_column('grid_cell_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('grid_cell_metrics', 'population_metric_is_placeholder')
    op.drop_column('grid_cell_metrics', 'population_metric_source')
    op.drop_column('grid_cell_metrics', 'visitor_metric_is_placeholder')
    op.drop_column('grid_cell_metrics', 'visitor_metric_source')
    op.drop_column('grid_cell_metrics', 'predicted_visitor_count')
    op.drop_column('grid_cell_metrics', 'predicted_population')
    op.drop_column('grid_cell_metrics', 'predicted_crowd_density')
    op.drop_column('grid_cell_metrics', 'predicted_heat_risk')
    op.drop_column('grid_cell_metrics', 'predicted_heat_index')
    op.drop_column('grid_cell_metrics', 'infrastructure_strain')
    op.drop_column('grid_cell_metrics', 'cooling_centers_impact_radius')
    op.drop_column('grid_cell_metrics', 'cooling_centers')
    op.drop_column('grid_cell_metrics', 'population')
    op.drop_column('grid_cell_metrics', 'crowd_density')
    op.drop_column('grid_cell_metrics', 'heat_risk')
    op.drop_column('grid_cell_metrics', 'heat_index')
    op.drop_column('grid_cell_metrics', 'timestamp')
    op.drop_constraint('uq_grid_cell_geometry_row_col_state', 'grid_cell_geometry', type_='unique')
    op.drop_constraint('uq_grid_cell_geometry_cell_id', 'grid_cell_geometry', type_='unique')
    op.drop_index(op.f('ix_grid_cell_geometry_row'), table_name='grid_cell_geometry')
    op.drop_index(op.f('ix_grid_cell_geometry_col'), table_name='grid_cell_geometry')
    op.drop_index(op.f('ix_grid_cell_geometry_cell_id'), table_name='grid_cell_geometry')
    op.create_unique_constraint(op.f('grid_cell_geometry_cell_id_key'), 'grid_cell_geometry', ['cell_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('grid_cell_geometry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('grid_cell_geometry', 'state',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'core_poi_geometry', type_='foreignkey')
    op.drop_index(op.f('ix_core_poi_geometry_store_id'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_safegraph_place_id'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_region'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_market'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_longitude'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_latitude'), table_name='core_poi_geometry')
    op.alter_column('core_poi_geometry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('core_poi_geometry', 'wkt_area_sq_meters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('core_poi_geometry', 'top_category_2022',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'top_category',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'sub_category_2022',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'sub_category',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'street_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'safegraph_place_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'region',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'postal_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'polygon_wkt',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'polygon_class',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'placekey',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'open_hours',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('core_poi_geometry', 'market',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('core_poi_geometry', 'location_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('core_poi_geometry', 'is_synthetic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'iso_country_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'includes_parking_lot',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'geometry_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'enclosed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'domains',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('core_poi_geometry', 'city',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_poi_geometry', 'category_tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('core_poi_geometry', 'brands',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_weather_observation_timestamp'), table_name='weather_observation')
    op.drop_index(op.f('ix_weather_observation_grid_cell_id'), table_name='weather_observation')
    op.drop_table('weather_observation')
    op.drop_index(op.f('ix_urban_heat_index_market'), table_name='urban_heat_index')
    op.drop_index(op.f('ix_urban_heat_index_longitude'), table_name='urban_heat_index')
    op.drop_index(op.f('ix_urban_heat_index_latitude'), table_name='urban_heat_index')
    op.drop_table('urban_heat_index')
    op.drop_index(op.f('ix_store_visits_rice_store_id'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_state'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_market'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_local_date'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_business_name'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_brand'), table_name='store_visits_rice')
    op.drop_table('store_visits_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_spend_date_range_start'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_spend_date_range_end'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_region'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_placekey'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_market'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_longitude'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_latitude'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_city'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_brands'), table_name='spend_patterns_rice')
    op.drop_table('spend_patterns_rice')
    op.drop_index(op.f('ix_polygon_impact_grids_polygon_geometry_id'), table_name='polygon_impact_grids')
    op.drop_index(op.f('ix_polygon_impact_grids_grid_cell_id'), table_name='polygon_impact_grids')
    op.drop_table('polygon_impact_grids')
    op.drop_index(op.f('ix_interpolated_points_timestamp'), table_name='interpolated_points')
    op.drop_index(op.f('ix_interpolated_points_grid_cell_id'), table_name='interpolated_points')
    op.drop_table('interpolated_points')
    op.drop_index(op.f('ix_daily_weather_rice_valid_date'), table_name='daily_weather_rice')
    op.drop_index(op.f('ix_daily_weather_rice_city_location_identifier'), table_name='daily_weather_rice')
    op.drop_table('daily_weather_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_trans_date'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_state_abbr'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_market'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_brand_name'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_brand_id'), table_name='daily_spend_brand_state_rice')
    op.drop_table('daily_spend_brand_state_rice')
    op.drop_table('visitor_data_ml')
    op.drop_index(op.f('ix_prediction_table_pred_model_name'), table_name='prediction_table')
    op.drop_index(op.f('ix_prediction_table_pred_longitude'), table_name='prediction_table')
    op.drop_index(op.f('ix_prediction_table_pred_latitude'), table_name='prediction_table')
    op.drop_table('prediction_table')
    op.drop_index(op.f('ix_polygon_geometry_state_name'), table_name='polygon_geometry')
    op.drop_index(op.f('ix_polygon_geometry_city_name'), table_name='polygon_geometry')
    op.drop_table('polygon_geometry')
    op.drop_index(op.f('ix_open_meteo_forecasts_longitude'), table_name='open_meteo_forecasts')
    op.drop_index(op.f('ix_open_meteo_forecasts_latitude'), table_name='open_meteo_forecasts')
    op.drop_index(op.f('ix_open_meteo_forecasts_fetched_at'), table_name='open_meteo_forecasts')
    op.drop_table('open_meteo_forecasts')
    op.drop_table('heat_data_ml')
    # ### end Alembic commands ###
