"""new users

Revision ID: 643080564cbe
Revises: 72ef5a710f97
Create Date: 2026-06-26 14:06:24.518433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643080564cbe'
down_revision: Union[str, Sequence[str], None] = '72ef5a710f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DATASET_USER_TABLES = (
    'core_poi_geometry',
    'daily_spend_brand_state_rice',
    'daily_weather_rice',
    'spend_patterns_rice',
    'store_visits_rice',
    'urban_heat_index',
)


def _fk_name(table_name: str) -> str:
    return f"fk_{table_name}_user_id_user"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    is_sqlite = op.get_bind().dialect.name == 'sqlite'

    for table_name in DATASET_USER_TABLES:
        op.add_column(table_name, sa.Column('user_id', sa.Integer(), nullable=True))
        if not is_sqlite:
            op.create_foreign_key(
                _fk_name(table_name),
                table_name,
                'user',
                ['user_id'],
                ['id'],
                ondelete='CASCADE',
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    is_sqlite = op.get_bind().dialect.name == 'sqlite'

    for table_name in reversed(DATASET_USER_TABLES):
        if not is_sqlite:
            op.drop_constraint(_fk_name(table_name), table_name, type_='foreignkey')
        op.drop_column(table_name, 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
