"""new columns

Revision ID: 6a75c07f2def
Revises: cd82239b2366
Create Date: 2026-06-29 14:11:28.977530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a75c07f2def'
down_revision: Union[str, Sequence[str], None] = 'cd82239b2366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid_cell_metrics', sa.Column('heat_index_color', sa.Text(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('heat_risk_color', sa.Text(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('crowd_density_color', sa.Text(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('population_color', sa.Text(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('cooling_centers_color', sa.Text(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('infrastructure_strain_color', sa.Text(), nullable=True))
    op.add_column('grid_cell_metrics', sa.Column('overall_risk_color', sa.Text(), nullable=True))
    op.drop_constraint(op.f('grid_cell_metrics_grid_cell_id_fkey'), 'grid_cell_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'grid_cell_metrics', 'grid_cell_geometry', ['grid_cell_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grid_cell_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('grid_cell_metrics_grid_cell_id_fkey'), 'grid_cell_metrics', 'grid_cell_geometry', ['grid_cell_id'], ['id'])
    op.drop_column('grid_cell_metrics', 'overall_risk_color')
    op.drop_column('grid_cell_metrics', 'infrastructure_strain_color')
    op.drop_column('grid_cell_metrics', 'cooling_centers_color')
    op.drop_column('grid_cell_metrics', 'population_color')
    op.drop_column('grid_cell_metrics', 'crowd_density_color')
    op.drop_column('grid_cell_metrics', 'heat_risk_color')
    op.drop_column('grid_cell_metrics', 'heat_index_color')
    # ### end Alembic commands ###
