"""added new created_at

Revision ID: 72ef5a710f97
Revises: df0a6ddddb0f
Create Date: 2026-06-26 11:07:34.847085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ef5a710f97'
down_revision: Union[str, Sequence[str], None] = 'df0a6ddddb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_visits_rice', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_visits_rice', 'created_at')
    # ### end Alembic commands ###
