"""adding first poi_geometry_column

Revision ID: a5c1d414286f
Revises: cb6acdc69007
Create Date: 2026-06-25 13:39:37.907058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c1d414286f'
down_revision: Union[str, Sequence[str], None] = 'cb6acdc69007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_poi_geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brands', sa.JSON(), nullable=True),
    sa.Column('category_tags', sa.JSON(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('enclosed', sa.Boolean(), nullable=False),
    sa.Column('geometry_type', sa.Text(), nullable=False),
    sa.Column('includes_parking_lot', sa.Boolean(), nullable=False),
    sa.Column('iso_country_code', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.Text(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('naics_code', sa.Integer(), nullable=True),
    sa.Column('naics_code_2022', sa.Integer(), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('open_hours', sa.JSON(), nullable=True),
    sa.Column('parent_placekey', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('placekey', sa.Text(), nullable=False),
    sa.Column('polygon_class', sa.Text(), nullable=False),
    sa.Column('polygon_wkt', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('safegraph_place_id', sa.Text(), nullable=False),
    sa.Column('store_id', sa.Text(), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=False),
    sa.Column('sub_category', sa.Text(), nullable=False),
    sa.Column('sub_category_2022', sa.Text(), nullable=False),
    sa.Column('top_category', sa.Text(), nullable=False),
    sa.Column('top_category_2022', sa.Text(), nullable=False),
    sa.Column('tracking_closed_since', sa.Date(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('wkt_area_sq_meters', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_poi_geometry')
    # ### end Alembic commands ###
