"""added new nws+table centric tables

Revision ID: cd82239b2366
Revises: 643080564cbe
Create Date: 2026-06-28 16:02:49.651232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd82239b2366'
down_revision: Union[str, Sequence[str], None] = '643080564cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_cell_geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Text(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('grid_centroid_lat', sa.Float(), nullable=False),
    sa.Column('grid_centroid_lon', sa.Float(), nullable=False),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_id', name='uq_grid_cell_geometry_cell_id'),
    sa.UniqueConstraint('row', 'col', 'state', name='uq_grid_cell_geometry_row_col_state')
    )
    op.create_index(op.f('ix_grid_cell_geometry_cell_id'), 'grid_cell_geometry', ['cell_id'], unique=False)
    op.create_index(op.f('ix_grid_cell_geometry_col'), 'grid_cell_geometry', ['col'], unique=False)
    op.create_index(op.f('ix_grid_cell_geometry_row'), 'grid_cell_geometry', ['row'], unique=False)
    op.create_index(op.f('ix_grid_cell_geometry_state'), 'grid_cell_geometry', ['state'], unique=False)
    op.create_table('grid_cell_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.Column('heat_risk', sa.Float(), nullable=True),
    sa.Column('crowd_density', sa.Float(), nullable=True),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('cooling_centers', sa.Integer(), nullable=True),
    sa.Column('cooling_centers_impact_radius', sa.Float(), nullable=True),
    sa.Column('infrastructure_strain', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cell_geometry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grid_cell_metrics_grid_cell_id'), 'grid_cell_metrics', ['grid_cell_id'], unique=False)
    op.create_index(op.f('ix_grid_cell_metrics_timestamp'), 'grid_cell_metrics', ['timestamp'], unique=False)
    op.create_table('weather_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('dewpoint', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Text(), nullable=True),
    sa.Column('precipitation_prob', sa.Float(), nullable=True),
    sa.Column('detailed_forecast', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cell_geometry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grid_cell_id', 'timestamp', 'source', name='uq_weather_observation_cell_timestamp_source')
    )
    op.create_index(op.f('ix_weather_observation_grid_cell_id'), 'weather_observation', ['grid_cell_id'], unique=False)
    op.create_index(op.f('ix_weather_observation_timestamp'), 'weather_observation', ['timestamp'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_city'), 'core_poi_geometry', ['city'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_latitude'), 'core_poi_geometry', ['latitude'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_longitude'), 'core_poi_geometry', ['longitude'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_market'), 'core_poi_geometry', ['market'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_placekey'), 'core_poi_geometry', ['placekey'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_region'), 'core_poi_geometry', ['region'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_safegraph_place_id'), 'core_poi_geometry', ['safegraph_place_id'], unique=False)
    op.create_index(op.f('ix_core_poi_geometry_store_id'), 'core_poi_geometry', ['store_id'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_brand_id'), 'daily_spend_brand_state_rice', ['brand_id'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_brand_name'), 'daily_spend_brand_state_rice', ['brand_name'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_market'), 'daily_spend_brand_state_rice', ['market'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_state_abbr'), 'daily_spend_brand_state_rice', ['state_abbr'], unique=False)
    op.create_index(op.f('ix_daily_spend_brand_state_rice_trans_date'), 'daily_spend_brand_state_rice', ['trans_date'], unique=False)
    op.create_index(op.f('ix_daily_weather_rice_city_location_identifier'), 'daily_weather_rice', ['city_location_identifier'], unique=False)
    op.create_index(op.f('ix_daily_weather_rice_valid_date'), 'daily_weather_rice', ['valid_date'], unique=False)
    op.create_index(op.f('ix_prediction_table_pred_latitude'), 'prediction_table', ['pred_latitude'], unique=False)
    op.create_index(op.f('ix_prediction_table_pred_longitude'), 'prediction_table', ['pred_longitude'], unique=False)
    op.create_index(op.f('ix_prediction_table_pred_model_name'), 'prediction_table', ['pred_model_name'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_brands'), 'spend_patterns_rice', ['brands'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_city'), 'spend_patterns_rice', ['city'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_latitude'), 'spend_patterns_rice', ['latitude'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_longitude'), 'spend_patterns_rice', ['longitude'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_market'), 'spend_patterns_rice', ['market'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_placekey'), 'spend_patterns_rice', ['placekey'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_region'), 'spend_patterns_rice', ['region'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_spend_date_range_end'), 'spend_patterns_rice', ['spend_date_range_end'], unique=False)
    op.create_index(op.f('ix_spend_patterns_rice_spend_date_range_start'), 'spend_patterns_rice', ['spend_date_range_start'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_brand'), 'store_visits_rice', ['brand'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_business_name'), 'store_visits_rice', ['business_name'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_local_date'), 'store_visits_rice', ['local_date'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_market'), 'store_visits_rice', ['market'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_state'), 'store_visits_rice', ['state'], unique=False)
    op.create_index(op.f('ix_store_visits_rice_store_id'), 'store_visits_rice', ['store_id'], unique=False)
    op.create_index(op.f('ix_urban_heat_index_latitude'), 'urban_heat_index', ['latitude'], unique=False)
    op.create_index(op.f('ix_urban_heat_index_longitude'), 'urban_heat_index', ['longitude'], unique=False)
    op.create_index(op.f('ix_urban_heat_index_market'), 'urban_heat_index', ['market'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_urban_heat_index_market'), table_name='urban_heat_index')
    op.drop_index(op.f('ix_urban_heat_index_longitude'), table_name='urban_heat_index')
    op.drop_index(op.f('ix_urban_heat_index_latitude'), table_name='urban_heat_index')
    op.drop_index(op.f('ix_store_visits_rice_store_id'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_state'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_market'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_local_date'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_business_name'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_store_visits_rice_brand'), table_name='store_visits_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_spend_date_range_start'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_spend_date_range_end'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_region'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_placekey'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_market'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_longitude'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_latitude'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_city'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_spend_patterns_rice_brands'), table_name='spend_patterns_rice')
    op.drop_index(op.f('ix_prediction_table_pred_model_name'), table_name='prediction_table')
    op.drop_index(op.f('ix_prediction_table_pred_longitude'), table_name='prediction_table')
    op.drop_index(op.f('ix_prediction_table_pred_latitude'), table_name='prediction_table')
    op.drop_index(op.f('ix_daily_weather_rice_valid_date'), table_name='daily_weather_rice')
    op.drop_index(op.f('ix_daily_weather_rice_city_location_identifier'), table_name='daily_weather_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_trans_date'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_state_abbr'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_market'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_brand_name'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_daily_spend_brand_state_rice_brand_id'), table_name='daily_spend_brand_state_rice')
    op.drop_index(op.f('ix_core_poi_geometry_store_id'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_safegraph_place_id'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_region'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_placekey'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_market'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_longitude'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_latitude'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_core_poi_geometry_city'), table_name='core_poi_geometry')
    op.drop_index(op.f('ix_weather_observation_timestamp'), table_name='weather_observation')
    op.drop_index(op.f('ix_weather_observation_grid_cell_id'), table_name='weather_observation')
    op.drop_table('weather_observation')
    op.drop_index(op.f('ix_grid_cell_metrics_timestamp'), table_name='grid_cell_metrics')
    op.drop_index(op.f('ix_grid_cell_metrics_grid_cell_id'), table_name='grid_cell_metrics')
    op.drop_table('grid_cell_metrics')
    op.drop_index(op.f('ix_grid_cell_geometry_state'), table_name='grid_cell_geometry')
    op.drop_index(op.f('ix_grid_cell_geometry_row'), table_name='grid_cell_geometry')
    op.drop_index(op.f('ix_grid_cell_geometry_col'), table_name='grid_cell_geometry')
    op.drop_index(op.f('ix_grid_cell_geometry_cell_id'), table_name='grid_cell_geometry')
    op.drop_table('grid_cell_geometry')
    # ### end Alembic commands ###
