"""fixed spendingtable

Revision ID: e3cf8eeaf0c4
Revises: dfdedd7ba1be
Create Date: 2026-07-06 12:17:25.815833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cf8eeaf0c4'
down_revision: Union[str, Sequence[str], None] = 'dfdedd7ba1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spend_patterns_rice', 'brands',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spend_patterns_rice', 'brands',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
