"""updating tables to include ml models visitor/heat

Revision ID: f38cde446d8f
Revises: d2e638727be0
Create Date: 2026-07-10 12:55:08.760563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38cde446d8f'
down_revision: Union[str, Sequence[str], None] = 'd2e638727be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heat_data_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('avg_temp_c', sa.Float(), nullable=False),
    sa.Column('relative_humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed_knots', sa.Float(), nullable=False),
    sa.Column('urban_heat_idx', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), server_default='interpolated', nullable=False),
    sa.Column('distance_nearest_station_km', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('passed_threshold', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitor_data_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('source_market', sa.Text(), nullable=True),
    sa.Column('fsq_place_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('visitor_count', sa.Integer(), nullable=True),
    sa.Column('visitor_count_source', sa.Text(), nullable=True),
    sa.Column('market_brand_visitor_count_total', sa.Integer(), nullable=True),
    sa.Column('candidate_foursquare_poi_count', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.Text(), nullable=True),
    sa.Column('visitor_categories', sa.Text(), nullable=True),
    sa.Column('nearest_heat_distance_km', sa.Float(), nullable=True),
    sa.Column('query_center_distance_m', sa.Float(), nullable=True),
    sa.Column('google_maps_congestion', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor_data_ml')
    op.drop_table('heat_data_ml')
    # ### end Alembic commands ###
